apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: relative-fawn
spec: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: relative-fawn
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      initContainers:
        - name: init-myservice
          image: busybox:1.36.1 # Example image for initialization tasks
          command: ['sh', '-c', 'echo "Initializing..." && sleep 5 && echo "Initialization complete."']
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
      containers:
        - name: my-app-container
          image: nginx:latest # Example main application container
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi