apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: autoscale
spec: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: apache-server
  name: apache-server
  namespace: autoscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apache-server
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}