apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: priority
spec: {}
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: busybox-logger
  name: busybox-logger
  namespace: priority
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-logger
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: busybox-logger
    spec:
      containers:
      - image: nginx
        name: busybox
        resources: {}
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: user-max-priority
value: 1000000
globalDefault: false
description: "user-max-priority."